from python:3.11-slim

env PIP_DISABLE_PIP_VERSION_CHECHK=1

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY  requirement.txt dest
run Python -m venv venv

RUN /bin/bash -c "source venv/bin/activate"

RUN pip install -r requirement.txt

COPY . .

EXPOSE 5000

CMD ["uvicorn", "app:py", "--reload", "--host", "0.0.0.0" "--port", "5000"]